spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_jwt
    username: postgres
    password: 91115101
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083
